# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./docker-react
    # Giving the container a name.
    container_name: clientapp_c
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"
    # Mapping the client directory on the host machine to the /app directory on the container.
    volumes:
      - ./docker-react:/app
      - /app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./docker-nodejs
    container_name: serverapp_c
    ports:
      - "5000:5000"
    volumes:
      - ./docker-nodejs:/app
      - /app/node_modules

# docker-compose up --build  => build the image and start a container
# docker-compose up --build -d 
# docker-compose down    => stop container and remove 


# docker build -t sachinsh1234/interview:client .  => build image for docker-react
# docker build -t sachinsh1234/interview:server.   => build image for docker-nodejs
# docker push sachinsh1234/interview:client  => push to dockerhub
# docker pull sachinsh1234/interview:client  => pull docker image